### ISSUE TITLE
hi dont wanna be that guy but the bot is down :)

### ISSUE THREAD

**Issue by itsyaboydavey** [matchatealeaf/albion-discord-bot#2]
hi dont wanna be that guy but the bot is down :)

**Comment by matchatealeaf** [comment]
Hi, I've check the logs and it wasn't down for a long time.
The bot might be slow to response, or miss your query entirely if there are too many requests at the same time.

Also, the github issues are reserved for bugs, questions about the bot's functionalities/codes, or suggestions of enhancements to the bot.
If the bot is down again, please direct your query to the forums, or drop me a message on discord.

Thanks.
