### ISSUE TITLE
Suggestion for decimal separator on prices presented by the bot

### ISSUE THREAD

**Issue by EricBAxe** [matchatealeaf/albion-discord-bot#4]
Would be greatly appreciated as currenty it can be hard to look at the numbers and instantly see the price.
Thanks for all the work on this great bot, keep up the good work!
-

**Comment by matchatealeaf** [comment]
Hi, thanks for the suggestion. I have added the separators.

41bf647db802498ba600c2fab76e2c6ce995b6ec
