### ISSUE TITLE
The bot doesn't work for me anymore. Need help.

### ISSUE THREAD

**Issue by arudaev** [matchatealeaf/albion-discord-bot#5]
![image](https://user-images.githubusercontent.com/66517969/114178672-b518e480-9946-11eb-96f3-7f92fe04f7e1.png)
Tried to kick it and inv it again, but didn't work. Please help me

**Comment by matchatealeaf** [comment]
Should be fixed now.

f6410be

**Comment by arudaev** [comment]
thank you for this great bot


сб, 10 апр. 2021 г. в 11:13, MatchaTeaLeaf ***@***.***>:
